### ISSUE TITLE
Access to NPM modules?

### ISSUE THREAD

**Issue by nixfreak** [juancarlospaco/nodejs#2]
Just curious if  nim nodjs will allow to import js modules say from NPM?

**Comment by juancarlospaco** [comment]
Anything on particular?, I dont know whats the most useful libraries for Node?.

It has a "sugar" module that has utilities, but is also kinda kitchen sink, so we need to sort it.

This is not part of the original idea, to use node modules you have to wrap it, we can not wrap everything on npm.

**Comment by nixfreak** [comment]
Yes I want to use nim for the stellar-SDK  https://github.com/stellar/js-stellar-sdk

To use the api on the stellar network.

**Comment by juancarlospaco** [comment]
I think you will have to wrap it, is what TypeScript does (stub they call it but is a kind of wrapper).

Is out of scope for this project, and we do not have any Sponsors for such developments...
